language: go
go:
- 1.x.x
deploy:
  provider: releases
  api_key:
    secure: kWn6XPJgc3m6B36cRao+DHSi8vNwVbJvi3VXRLUSHmJj295npu24VDm7QuHr1POKW8KVVPeiycQVJR3nbp8VezLnpreCWubfyuaS+Goz4YtDEzxDevzYVe4py3KqM4MJ+O0b9jXjIDrfh58KqKa7SD798TdCxs+pGHlRZmlOTxkrKwJvBNHKUpA+tRbJCB+gkPQ73XEaUnrLgaItPNWScAh4oNdqMAj/TeabBB/POQtYtHb4WTzV42GY61UCnlnDbrds6jnidIL5Yp1C0CFhIsRKdEiWsHuwCd2Qlg9HSQHtMeinlW13cVhAfA1FhiBpMCuVKiQvsNls1ceqR9fpHrSLFSlzDQXAFzftqM2OBgXb1pyj3TyDxjnEJsrTYE0Sn6Fh49MeHjIbSIh8uvIDwkWeJIGbTHafvnwWlbX7PfgNXrMmdofQc+rjxzKSXrUHus29T3WTB2rEZyY++A17S/r8IQdqhbtPmoi4ZUCeaRCwfOOrUCtbblQSn22o4Gcm81XmRU1v9ncHVs5JX8gE16ChTI4+EK1mEvjyFlpqd4QPBABoEJ23DVxKHDzfpRyoljfGvx1dWJbiulV+1Wcu/0b4Hrm12r4AC6Sd+74EVZEMFfXwXZmyiq+gu/xxKRMlMzbO/oE9v02OH2/WXXC2keJxMm6hVsOKsK0T7SZO17E=
  file: bin/check_snmp_hpsw
  skip_cleanup: true
  on:
    repo: fenderle/check_snmp_hpsw
    tags: true
