language: go
go:
  - 1.x.x

env:
  - OS=linux   ARCH=386
  - OS=linux   ARCH=amd64
  - OS=freebsd ARCH=386
  - OS=freebsd ARCH=amd64
  - OS=netbsd  ARCH=386
  - OS=netbsd  ARCH=amd64

before_install:
  - go get github.com/mitchellh/gox

script:
  - go get -t -v ./...
  - mkdir -p ${OS}-${ARCH}
  - cp README.md LICENSE ${OS}-${ARCH}
  - gox -osarch="${OS}/${ARCH}" -output="{{.OS}}-{{.Arch}}/check_snmp_hpsw" ./...
  - tar cvzf check_snmp_hpsw-linux-${ARCH}.tar.gz linux-${ARCH}
  - zip -r check_snmp_hpsw-linux-${ARCH}.zip linux-${ARCH}

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kWn6XPJgc3m6B36cRao+DHSi8vNwVbJvi3VXRLUSHmJj295npu24VDm7QuHr1POKW8KVVPeiycQVJR3nbp8VezLnpreCWubfyuaS+Goz4YtDEzxDevzYVe4py3KqM4MJ+O0b9jXjIDrfh58KqKa7SD798TdCxs+pGHlRZmlOTxkrKwJvBNHKUpA+tRbJCB+gkPQ73XEaUnrLgaItPNWScAh4oNdqMAj/TeabBB/POQtYtHb4WTzV42GY61UCnlnDbrds6jnidIL5Yp1C0CFhIsRKdEiWsHuwCd2Qlg9HSQHtMeinlW13cVhAfA1FhiBpMCuVKiQvsNls1ceqR9fpHrSLFSlzDQXAFzftqM2OBgXb1pyj3TyDxjnEJsrTYE0Sn6Fh49MeHjIbSIh8uvIDwkWeJIGbTHafvnwWlbX7PfgNXrMmdofQc+rjxzKSXrUHus29T3WTB2rEZyY++A17S/r8IQdqhbtPmoi4ZUCeaRCwfOOrUCtbblQSn22o4Gcm81XmRU1v9ncHVs5JX8gE16ChTI4+EK1mEvjyFlpqd4QPBABoEJ23DVxKHDzfpRyoljfGvx1dWJbiulV+1Wcu/0b4Hrm12r4AC6Sd+74EVZEMFfXwXZmyiq+gu/xxKRMlMzbO/oE9v02OH2/WXXC2keJxMm6hVsOKsK0T7SZO17E=
  file:
    - check_snmp_hpsw-${OS}-${ARCH}.tar.gz
    - check_snmp_hpsw-${OS}-${ARCH}.zip
  on:
    repo: fenderle/check_snmp_hpsw
    tags: false
